name: cookieclicker
description: "A cookie clicker application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  sembast: ^3.7.5
  get_it: ^8.0.1
  path_provider: ^2.0.11
  path: ^1.8.0
  dropdown_search: ^5.0.3
  crypto: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cookie.png
    - assets/background.png
    - assets/background2.png